# Setup
title:        Dr Kai Wang
tagline:      kaiwang.tech
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Dr Kai Wang
  url:        http://kaiwang.tech

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 96ca30748ba77233e445acf4d88fecb2
google_analytics_id: UA-114578002-1 # google 分析追踪id

exclude:
         - vendor
         - Gemfile
         - Gemfile.lock
         - node_modules
         - gulpfile.js
         - package.json

