# Setup
title:        Dr Kai Wang's Tech Site
tagline:      kaiwang.tech
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Dr Kai Wang
  url:        http://kaiwang.tech

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
